// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3uKAIewQvuW2SKJIuZYo2MPUG9exi5-c',
    appId: '1:633541052804:web:57a82ede31361f453f35d1',
    messagingSenderId: '633541052804',
    projectId: 'healanddeal-591d6',
    authDomain: 'healanddeal-591d6.firebaseapp.com',
    storageBucket: 'healanddeal-591d6.appspot.com',
    measurementId: 'G-MXQTE7V6EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXHcZx0h9NpgSFZb9ePDO28S5vkVbA5Ys',
    appId: '1:633541052804:android:6a9734805ff2a1623f35d1',
    messagingSenderId: '633541052804',
    projectId: 'healanddeal-591d6',
    storageBucket: 'healanddeal-591d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUI04U8SUf-KVGJxVv7m_ljkjImlQRKwo',
    appId: '1:633541052804:ios:18c6c05d4d0434273f35d1',
    messagingSenderId: '633541052804',
    projectId: 'healanddeal-591d6',
    storageBucket: 'healanddeal-591d6.appspot.com',
    androidClientId: '633541052804-9jptchj3gduao7k0ijv109t0n983manh.apps.googleusercontent.com',
    iosClientId: '633541052804-qmn7cbgn6nigbhhhuf93fccgntm8qclb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fearless',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUI04U8SUf-KVGJxVv7m_ljkjImlQRKwo',
    appId: '1:633541052804:ios:18c6c05d4d0434273f35d1',
    messagingSenderId: '633541052804',
    projectId: 'healanddeal-591d6',
    storageBucket: 'healanddeal-591d6.appspot.com',
    androidClientId: '633541052804-9jptchj3gduao7k0ijv109t0n983manh.apps.googleusercontent.com',
    iosClientId: '633541052804-qmn7cbgn6nigbhhhuf93fccgntm8qclb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fearless',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3uKAIewQvuW2SKJIuZYo2MPUG9exi5-c',
    appId: '1:633541052804:web:6108fde725e10f1b3f35d1',
    messagingSenderId: '633541052804',
    projectId: 'healanddeal-591d6',
    authDomain: 'healanddeal-591d6.firebaseapp.com',
    storageBucket: 'healanddeal-591d6.appspot.com',
    measurementId: 'G-71GB4PG6WF',
  );
}
